version: "3.9"
services:
  ap:
    build:
      context: .docker/ap
    #   args:
    #     USER:
    #     UID: 1000
    #     GROUP: ${USER}
    #     GID: 1000
    #     APP_HOME: /workspace
    #     DB: sqlite3
    #     DB: mysql
    #     DB: postgresql
    #     DB: sqlserver
    # entrypoint: []
    # command: bash
    # stdin_open: true
    # tty: true
    ports:
      - "3000:3000"
    # environment:
    #   TZ: Asia/Tokyo
    #   RAILS_MASTER_KEY:
    #   SA_PASSWORD: <YourStrong!Passw0rd>
    # env_file:
    #   - .env
    # volumes:
    #   - .:/workspace
    # tmpfs:
    #   - /tmp
    #   - /workspace/tmp/pids:uid=1000,gid=1000

  # Use only either ap or debug.
  debug:
    extends:
      service: ap
    ports:
      - "1234:1234"
    command:
      - bash
      - -c
      - |
        sudo -E gem install ruby-debug-ide
        sudo -E gem install debase
        rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails server -b 0.0.0.0
    restart: always
    profiles: ["muted"]

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      default:
        aliases: [db]
    profiles: ["muted"]

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      default:
        aliases: [db]
    profiles: ["muted"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: <YourStrong!Passw0rd>
    networks:
      default:
        aliases: [db]
    profiles: ["muted"]
